{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Градиентный бустинг своими руками\n",
    "\n",
    "**Внимание:** в тексте задания произошли изменения - поменялось число деревьев (теперь 50), правило изменения величины шага в задании 3 и добавился параметр `random_state` у решающего дерева. Правильные ответы не поменялись, но теперь их проще получить. Также исправлена опечатка в функции `gbm_predict`.\n",
    "\n",
    "В этом задании будет использоваться датасет `boston` из `sklearn.datasets`. Оставьте последние 25% объектов для контроля качества, разделив `X` и `y` на `X_train`, `y_train` и `X_test`, `y_test`.\n",
    "\n",
    "Целью задания будет реализовать простой вариант градиентного бустинга над регрессионными деревьями для случая квадратичной функции потерь."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn import ensemble, datasets, model_selection, tree, metrics, linear_model\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "boston = datasets.load_boston()\n",
    "X = boston.data\n",
    "y = boston.target\n",
    "\n",
    "#X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, test_size=0.25)\n",
    "lim = len(y) - round(0.25*len(y))\n",
    "X_train, X_test = X[:lim-1], X[lim:]\n",
    "y_train, y_test = y[:lim-1], y[lim:]"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Задание 1\n",
    "\n",
    "Как вы уже знаете из лекций, **бустинг** - это метод построения композиций базовых алгоритмов с помощью последовательного добавления к текущей композиции нового алгоритма с некоторым коэффициентом. \n",
    "\n",
    "Градиентный бустинг обучает каждый новый алгоритм так, чтобы он приближал антиградиент ошибки по ответам композиции на обучающей выборке. Аналогично минимизации функций методом градиентного спуска, в градиентном бустинге мы подправляем композицию, изменяя алгоритм в направлении антиградиента ошибки.\n",
    "\n",
    "Воспользуйтесь формулой из лекций, задающей ответы на обучающей выборке, на которые нужно обучать новый алгоритм (фактически это лишь чуть более подробно расписанный градиент от ошибки), и получите частный ее случай, если функция потерь `L` - квадрат отклонения ответа композиции `a(x)` от правильного ответа `y` на данном `x`.\n",
    "\n",
    "Если вы давно не считали производную самостоятельно, вам поможет таблица производных элементарных функций (которую несложно найти в интернете) и правило дифференцирования сложной функции. После дифференцирования квадрата у вас возникнет множитель 2 — т.к. нам все равно предстоит выбирать коэффициент, с которым будет добавлен новый базовый алгоритм, проигноируйте этот множитель при дальнейшем построении алгоритма."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "#very strange task =)\n",
    "def s(a, y,coef):\n",
    "    return -(a(X_train) - y)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Задание 2\n",
    "\n",
    "Заведите массив для объектов `DecisionTreeRegressor` (будем их использовать в качестве базовых алгоритмов) и для вещественных чисел (это будут коэффициенты перед базовыми алгоритмами). \n",
    "\n",
    "В цикле от обучите последовательно 50 решающих деревьев с параметрами `max_depth=5` и `random_state=42` (остальные параметры - по умолчанию). В бустинге зачастую используются сотни и тысячи деревьев, но мы ограничимся 50, чтобы алгоритм работал быстрее, и его было проще отлаживать (т.к. цель задания разобраться, как работает метод). Каждое дерево должно обучаться на одном и том же множестве объектов, но ответы, которые учится прогнозировать дерево, будут меняться в соответствие с полученным в задании 1 правилом. \n",
    "\n",
    "Попробуйте для начала всегда брать коэффициент равным 0.9. Обычно оправдано выбирать коэффициент значительно меньшим - порядка 0.05 или 0.1, но т.к. в нашем учебном примере на стандартном датасете будет всего 50 деревьев, возьмем для начала шаг побольше.\n",
    "\n",
    "В процессе реализации обучения вам потребуется функция, которая будет вычислять прогноз построенной на данный момент композиции деревьев на выборке `X`:\n",
    "\n",
    "```\n",
    "def gbm_predict(X):\n",
    "    return [sum([coeff * algo.predict([x])[0] for algo, coeff in zip(base_algorithms_list, coefficients_list)]) for x in X]\n",
    "(считаем, что base_algorithms_list - список с базовыми алгоритмами, coefficients_list - список с коэффициентами перед алгоритмами)\n",
    "```\n",
    "\n",
    "Эта же функция поможет вам получить прогноз на контрольной выборке и оценить качество работы вашего алгоритма с помощью `mean_squared_error` в `sklearn.metrics`. \n",
    "\n",
    "Возведите результат в степень 0.5, чтобы получить `RMSE`. Полученное значение `RMSE` — **ответ в пункте 2**."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "5.466320488281128\n"
     ]
    }
   ],
   "source": [
    "base_algorithms_list = []\n",
    "coefficients_list = [0.9 for i in range(50)]\n",
    "\n",
    "def gbm_predict(X):\n",
    "    return [sum([coeff * algo.predict([x])[0] for algo, coeff in zip(base_algorithms_list, coefficients_list)]) for x in X]\n",
    "\n",
    "\n",
    "s = y_train\n",
    "for i in range(50):\n",
    "    regressor_tree = tree.DecisionTreeRegressor(random_state=42, max_depth=5)\n",
    "    regressor_tree.fit(X_train, s)\n",
    "    base_algorithms_list.append(regressor_tree)\n",
    "    s = -(gbm_predict(X_train)-y_train)\n",
    "    \n",
    "    \n",
    "print(metrics.mean_squared_error(y_test, gbm_predict(X_test))**0.5)    "
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Задание 3\n",
    "\n",
    "Вас может также беспокоить, что двигаясь с постоянным шагом, вблизи минимума ошибки ответы на обучающей выборке меняются слишком резко, перескакивая через минимум. \n",
    "\n",
    "Попробуйте уменьшать вес перед каждым алгоритмом с каждой следующей итерацией по формуле `0.9 / (1.0 + i)`, где `i` - номер итерации (от 0 до 49). Используйте качество работы алгоритма как **ответ в пункте 3**. \n",
    "\n",
    "В реальности часто применяется следующая стратегия выбора шага: как только выбран алгоритм, подберем коэффициент перед ним численным методом оптимизации таким образом, чтобы отклонение от правильных ответов было минимальным. Мы не будем предлагать вам реализовать это для выполнения задания, но рекомендуем попробовать разобраться с такой стратегией и реализовать ее при случае для себя."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "4.819270353266556\n"
     ]
    }
   ],
   "source": [
    "coefficients_list = [0.9/(1+i) for i in range(50)]\n",
    "base_algorithms_list = []\n",
    "\n",
    "def gbm_predict(X):\n",
    "    return [sum([coeff * algo.predict([x])[0] for algo, coeff in zip(base_algorithms_list, coefficients_list)]) for x in X]\n",
    "\n",
    "\n",
    "s = y_train\n",
    "for i in range(50):\n",
    "    regressor_tree = tree.DecisionTreeRegressor(random_state=42, max_depth=5)\n",
    "    regressor_tree.fit(X_train, s)\n",
    "    base_algorithms_list.append(regressor_tree)\n",
    "    s = -(gbm_predict(X_train)-y_train)\n",
    "    \n",
    "    \n",
    "print(metrics.mean_squared_error(y_test, gbm_predict(X_test))**0.5)    "
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Задание 4\n",
    "\n",
    "Реализованный вами метод - градиентный бустинг над деревьями - очень популярен в машинном обучении. Он представлен как в самой библиотеке `sklearn`, так и в сторонней библиотеке `XGBoost`, которая имеет свой питоновский интерфейс. На практике `XGBoost` работает заметно лучше `GradientBoostingRegressor` из `sklearn`, но для этого задания вы можете использовать любую реализацию. \n",
    "\n",
    "Исследуйте, переобучается ли градиентный бустинг с ростом числа итераций (и подумайте, почему), а также с ростом глубины деревьев. На основе наблюдений выпишите через пробел номера правильных из приведенных ниже утверждений в порядке возрастания номера (это будет **ответ в п.4**):\n",
    "\n",
    "    1. С увеличением числа деревьев, начиная с некоторого момента, качество работы градиентного бустинга не меняется существенно.\n",
    "\n",
    "    2. С увеличением числа деревьев, начиная с некоторого момента, градиентный бустинг начинает переобучаться.\n",
    "\n",
    "    3. С ростом глубины деревьев, начиная с некоторого момента, качество работы градиентного бустинга на тестовой выборке начинает ухудшаться.\n",
    "\n",
    "    4. С ростом глубины деревьев, начиная с некоторого момента, качество работы градиентного бустинга перестает существенно изменяться"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "def plot_scores(x, y, name=''):\n",
    "  \n",
    "  plt.grid(True)\n",
    "  plt.plot(x,  y)\n",
    "  plt.xlabel('Parameters')\n",
    "  plt.ylabel('MSE')\n",
    "  plt.title(name)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n"
     ]
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAZAAAAEWCAYAAABIVsEJAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjMuNCwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy8QVMy6AAAACXBIWXMAAAsTAAALEwEAmpwYAAAVrUlEQVR4nO3dfZBldX3n8ffHwcmioMgiLc6gAzpGRisx7BRiTHZ7V3EZtMCtTZWwUVDXnaJWjEZTiiG1MX+45UMSEWGdHZ8KIsqaklRmySgi2rWSDS5CECVIGCcSRkbwISoNKEG++8c9Yy6d2317fj23b/fc96vqVp+H3znn+51b8OnzcG+nqpAkaX89ZtwFSJJWJwNEktTEAJEkNTFAJElNDBBJUhMDRJLUxACRVqgks0mOH3cd0nwMEGkeSb6V5MVJXp3kuhEfaybJ6/qXVdVhVbV7lMeVlsIAkUYsySHjrkEaBQNEWtgJwDbgBd0lpR8CJPmFJH+Y5O+T3JNkW5JDu3XTSfYkeVuS7wAfS/KkJFcl+W6Sf+im13fj3wn8OnBxd4yLu+WV5Jnd9BOTXNZtf2eS30vymG7dq5Nc19XzD0n+LsmWfQ1063cnua9b95vL98+ng5kBIi3sNuBc4K+6S0pHdMvfDTwLeB7wTGAd8N/6tnsKcCTwdGArvf/WPtbNPw14ELgYoKouAL4EnNcd47wBdXwAeCJwPPBvgLOB1/Stfz5wO3AU8B7gI+l5PHARsKWqDgd+Fbi57Z9CejQDRNpPSQL8F+C3q+oHVXUf8N+BM/uGPQL8flX9tKoerKrvV9Wnq+qBbvw76QXBYo63BngF8Paquq+qvgX8EfCqvmF3VtWHqupnwKXAMcBUXy3PTXJoVe2tqlubm5f6GCDS/nsy8DjgxiQ/7C5rfbZbvs93q+on+2aSPC7J/+wuP/0Y+D/AEV04DHMUsBa4s2/ZnfTOevb5zr6Jqnqgmzysqu6nFz7nAnuT/EWSZy+2UWkhBog03NyvrP4evUtQz6mqI7rXE6vqsAW2eQvwi8Dzq+oJwL/ulmee8XOP94/0Ln/t8zTg24sqvurqqjqF3lnJN4APLWY7aRgDRBruHmB9krUAVfUIvf8Jvy/J0QBJ1iX59wvs43B6ofPDJEcCvz/gGAM/89FdlvoU8M4khyd5OvBm4OPDCk8yleT07l7IT4FZ4GfDtpMWwwCRhvsCcCvwnSTf65a9DdgFXN9dkvo8vTOM+VwIHErvbOJ6epe8+r0f+I3uKaqLBmz/BuB+YDdwHfAJ4KOLqP0x9M5+7gZ+QO++y39dxHbSUPEPSkmSWngGIklqYoBIkpoYIJKkJgaIJKnJRH3J21FHHVUbNmwYdxn77f777+fxj3/8uMtYNpPWL9jzpFitPd94443fq6onz10+UQGyYcMGvvKVr4y7jP02MzPD9PT0uMtYNpPWL9jzpFitPSe5c9ByL2FJkpoYIJKkJgaIJKmJASJJamKASJKaGCCSpCYGiCSpiQEiSWpigEiSmhggkqQmBogkqYkBIklqYoBIkpoYIJKkJgaIJKmJASJJamKASJKaGCCSpCYGiCSpiQEiSWpigEiSmhggkqQmBogkqYkBIklqYoBIkpqMNUCSnJrk9iS7kpw/YH2SXNStvyXJiXPWr0ny10muWr6qJUkwxgBJsga4BNgCbALOSrJpzrAtwMbutRX44Jz1bwRuG3GpkqQBxnkGchKwq6p2V9VDwBXAGXPGnAFcVj3XA0ckOQYgyXrgpcCHl7NoSVLPIWM89jrgrr75PcDzFzFmHbAXuBB4K3D4QgdJspXe2QtTU1PMzMwspeaxmJ2dXZV1t5q0fsGeJ8XB1vM4AyQDltVixiR5GXBvVd2YZHqhg1TVdmA7wObNm2t6esHhK9LMzAyrse5Wk9Yv2POkONh6HuclrD3AsX3z64G7FznmhcDpSb5F79LXv0vy8dGVKkmaa5wBcgOwMclxSdYCZwI75ozZAZzdPY11MvCjqtpbVW+vqvVVtaHb7gtV9cplrV6SJtzYLmFV1cNJzgOuBtYAH62qW5Oc263fBuwETgN2AQ8ArxlXvZKkRxvnPRCqaie9kOhftq1vuoDXD9nHDDAzgvIkSQvwk+iSpCYGiCSpiQEiSWpigEiSmhggkqQmBogkqYkBIklqYoBIkpoYIJKkJgaIJKmJASJJamKASJKaGCCSpCYGiCSpiQEiSWpigEiSmhggkqQmBogkqYkBIklqYoBIkpoYIJKkJgaIJKmJASJJamKASJKaGCCSpCYGiCSpiQEiSWpigEiSmhggkqQmBogkqclYAyTJqUluT7IryfkD1ifJRd36W5Kc2C0/NskXk9yW5NYkb1z+6iVpso0tQJKsAS4BtgCbgLOSbJozbAuwsXttBT7YLX8YeEtVnQCcDLx+wLaSpBEa5xnIScCuqtpdVQ8BVwBnzBlzBnBZ9VwPHJHkmKraW1U3AVTVfcBtwLrlLF6SJt04A2QdcFff/B7+eQgMHZNkA/ArwJcPfImSpPkcMsZjZ8Cy2p8xSQ4DPg28qap+PPAgyVZ6l7+YmppiZmamqdhxmp2dXZV1t5q0fsGeJ8XB1vM4A2QPcGzf/Hrg7sWOSfJYeuFxeVVdOd9Bqmo7sB1g8+bNNT09veTCl9vMzAyrse5Wk9Yv2POkONh6HuclrBuAjUmOS7IWOBPYMWfMDuDs7mmsk4EfVdXeJAE+AtxWVX+8vGVLkmCMZyBV9XCS84CrgTXAR6vq1iTnduu3ATuB04BdwAPAa7rNXwi8Cvhakpu7Zb9bVTuXsQVJmmjjvIRF9z/8nXOWbeubLuD1A7a7jsH3RyRJy8RPokuSmhggkqQmBogkqYkBIklqYoBIkpoYIJKkJgaIJKmJASJJamKASJKaGCCSpCYGiCSpiQEiSWpigEiSmhggkqQmBogkqYkBIklqYoBIkpoYIJKkJgaIJKmJASJJamKASJKaGCCSpCYGiCSpiQEiSWpigEiSmhggkqQmCwZIklf2Tb9wzrrzRlWUJGnlG3YG8ua+6Q/MWffaA1yLJGkVGRYgmWd60LwkaYIMC5CaZ3rQvCRpghwyZP2zk9xC72zjGd003fzxI61MkrSiDQuQE0Z58CSnAu8H1gAfrqp3zVmfbv1pwAPAq6vqpsVsK0karQUvYVXVnf0vYBY4ETiqm2+WZA1wCbAF2ASclWTTnGFbgI3dayvwwf3YVpI0QsMe470qyXO76WOAr9N7+upPkrxpicc+CdhVVbur6iHgCuCMOWPOAC6rnuuBI7o6FrOtJGmEhl3COq6qvt5Nvwa4pqrOTnI48JfAhUs49jrgrr75PcDzFzFm3SK3BSDJVnpnL0xNTTEzM7OEksdjdnZ2VdbdatL6BXueFAdbz8MC5B/7pl8EfAigqu5L8sgSjz3oMeC5T3bNN2Yx2/YWVm0HtgNs3ry5pqen96PElWFmZobVWHerSesX7HlSHGw9DwuQu5K8gd5v+CcCnwVIcijw2CUeew9wbN/8euDuRY5Zu4htJUkjNOxzIP8ZeA7wauAVVfXDbvnJwMeWeOwbgI1JjkuyFjgT2DFnzA7g7PScDPyoqvYucltJ0ggteAZSVfcC5w5Y/kXgi0s5cFU93H2f1tX0HsX9aFXdmuTcbv02YCe9R3h30XuM9zULbbuUeiRJ+2fBAEmy4G/1VXX6Ug5eVTvphUT/sm190wW8frHbSpKWz7B7IC+g97TTJ4Ev4/dfSZI6wwLkKcApwFnAfwL+Avikl4skScM+if6zqvpsVZ1D78b5LmCmezJLkjTBhp2BkOQXgJfSOwvZAFwEXDnasiRJK92wm+iXAs8FPgP8Qd+n0iVJE27YGcirgPuBZwG/1ftyXKB3M72q6gkjrE2StIIN+xzIsA8aSpImlAEhSWpigEiSmhggkqQmBogkqYkBIklqYoBIkpoYIJKkJgaIJKmJASJJamKASJKaGCCSpCYGiCSpiQEiSWpigEiSmhggkqQmBogkqYkBIklqYoBIkpoYIJKkJgaIJKmJASJJamKASJKaGCCSpCZjCZAkRya5Jskd3c8nzTPu1CS3J9mV5Py+5e9N8o0ktyT5syRHLFvxkiRgfGcg5wPXVtVG4Npu/lGSrAEuAbYAm4CzkmzqVl8DPLeqfgn4W+Dty1K1JOnnxhUgZwCXdtOXAi8fMOYkYFdV7a6qh4Aruu2oqs9V1cPduOuB9aMtV5I017gCZKqq9gJ0P48eMGYdcFff/J5u2VyvBT5zwCuUJC3okFHtOMnngacMWHXBYncxYFnNOcYFwMPA5QvUsRXYCjA1NcXMzMwiD79yzM7Orsq6W01av2DPk+Jg63lkAVJVL55vXZJ7khxTVXuTHAPcO2DYHuDYvvn1wN19+zgHeBnwoqoq5lFV24HtAJs3b67p6en96mMlmJmZYTXW3WrS+gV7nhQHW8/juoS1Azinmz4H+PMBY24ANiY5Lsla4MxuO5KcCrwNOL2qHliGeiVJc4wrQN4FnJLkDuCUbp4kT02yE6C7SX4ecDVwG/Cpqrq12/5i4HDgmiQ3J9m23A1I0qQb2SWshVTV94EXDVh+N3Ba3/xOYOeAcc8caYGSpKH8JLokqYkBIklqYoBIkpoYIJKkJgaIJKmJASJJamKASJKaGCCSpCYGiCSpiQEiSWpigEiSmhggkqQmBogkqYkBIklqYoBIkpoYIJKkJgaIJKmJASJJamKASJKaGCCSpCYGiCSpiQEiSWpigEiSmhggkqQmBogkqYkBIklqYoBIkpoYIJKkJgaIJKmJASJJamKASJKajCVAkhyZ5Jokd3Q/nzTPuFOT3J5kV5LzB6z/nSSV5KjRVy1J6jeuM5DzgWuraiNwbTf/KEnWAJcAW4BNwFlJNvWtPxY4Bfj7ZalYkvQo4wqQM4BLu+lLgZcPGHMSsKuqdlfVQ8AV3Xb7vA94K1AjrFOSNI9DxnTcqaraC1BVe5McPWDMOuCuvvk9wPMBkpwOfLuqvppkwQMl2QpsBZiammJmZmbp1S+z2dnZVVl3q0nrF+x5UhxsPY8sQJJ8HnjKgFUXLHYXA5ZVksd1+3jJYnZSVduB7QCbN2+u6enpRR5+5ZiZmWE11t1q0voFe54UB1vPIwuQqnrxfOuS3JPkmO7s4xjg3gHD9gDH9s2vB+4GngEcB+w7+1gP3JTkpKr6zgFrQJK0oHHdA9kBnNNNnwP8+YAxNwAbkxyXZC1wJrCjqr5WVUdX1Yaq2kAvaE40PCRpeY0rQN4FnJLkDnpPUr0LIMlTk+wEqKqHgfOAq4HbgE9V1a1jqleSNMdYbqJX1feBFw1YfjdwWt/8TmDnkH1tOND1SZKG85PokqQmBogkqYkBIklqYoBIkpoYIJKkJgaIJKmJASJJamKASJKaGCCSpCYGiCSpiQEiSWpigEiSmhggkqQmBogkqYkBIklqYoBIkpoYIJKkJgaIJKmJASJJamKASJKaGCCSpCYGiCSpiQEiSWpigEiSmqSqxl3DsknyXeDOcdfR4Cjge+MuYhlNWr9gz5Nitfb89Kp68tyFExUgq1WSr1TV5nHXsVwmrV+w50lxsPXsJSxJUhMDRJLUxABZHbaPu4BlNmn9gj1PioOqZ++BSJKaeAYiSWpigEiSmhggK0CSI5Nck+SO7ueT5hl3apLbk+xKcv6A9b+TpJIcNfqql2apPSd5b5JvJLklyZ8lOWLZit9Pi3jfkuSibv0tSU5c7LYrVWvPSY5N8sUktyW5Nckbl7/6Nkt5n7v1a5L8dZKrlq/qJaoqX2N+Ae8Bzu+mzwfePWDMGuCbwPHAWuCrwKa+9ccCV9P7oORR4+5p1D0DLwEO6abfPWj7lfAa9r51Y04DPgMEOBn48mK3XYmvJfZ8DHBiN3048LcHe899698MfAK4atz9LPblGcjKcAZwaTd9KfDyAWNOAnZV1e6qegi4ottun/cBbwVWy1MRS+q5qj5XVQ93464H1o+23GbD3je6+cuq53rgiCTHLHLblai556raW1U3AVTVfcBtwLrlLL7RUt5nkqwHXgp8eDmLXioDZGWYqqq9AN3PoweMWQfc1Te/p1tGktOBb1fVV0dd6AG0pJ7neC293+xWosX0MN+Yxfa/0iyl559LsgH4FeDLB77EA26pPV9I7xfAR0ZU30gcMu4CJkWSzwNPGbDqgsXuYsCySvK4bh8vaa1tVEbV85xjXAA8DFy+f9Utm6E9LDBmMduuREvpubcyOQz4NPCmqvrxAaxtVJp7TvIy4N6qujHJ9IEubJQMkGVSVS+eb12Se/advnentPcOGLaH3n2OfdYDdwPPAI4Dvppk3/KbkpxUVd85YA00GGHP+/ZxDvAy4EXVXURegRbsYciYtYvYdiVaSs8keSy98Li8qq4cYZ0H0lJ6/g3g9CSnAf8CeEKSj1fVK0dY74Ex7pswvgrgvTz6hvJ7Bow5BNhNLyz23aR7zoBx32J13ERfUs/AqcDfAE8edy9D+hz6vtG79t1/c/X/7c97vtJeS+w5wGXAhePuY7l6njNmmlV0E33sBfgqgH8JXAvc0f08slv+VGBn37jT6D2V8k3ggnn2tVoCZEk9A7voXU++uXttG3dPC/T6z3oAzgXO7aYDXNKt/xqweX/e85X4au0Z+DV6l35u6XtvTxt3P6N+n/v2saoCxK8ykSQ18SksSVITA0SS1MQAkSQ1MUAkSU0MEElSEwNEmkeSnyW5OcnXk/xp96n/cdc0neRXx12HBAaItJAHq+p5VfVc4CF6z/QPlWSU3/AwDexXgIy4Hk0wPwcizSPJbFUd1k2fC/wSvU8S/x69Txt/H/jNqronyTvofQhyA/A94HeBPwEe3+3uvKr6v913Hf0BcA/wPOBKeh8qeyNwKPDyqvpmkicD24Cnddu/Cfg2vW8e/hnwXeANwDfmjquqvxxQzzuBj3V1Pwb4j1V1xwH4Z9IE8zcTaYjuN/gtwGeB64CTq6qSvI7eN6i+pRv6r4Bfq6oHu8tdp1TVT5JsBD4JbO7G/TJwAvADel9/8eGqOqn740lvoBcW7wfeV1XXJXkacHVVnZBkGzBbVX/Y1faJueO6fc+t5wPA+6vq8iRr6f39CmlJDBBpfocmubmb/hLwEeAXgf/VfQHkWuDv+sbvqKoHu+nHAhcneR69M4Zn9Y27obqvsk/yTeBz3fKvAf+2m34xsKn7gkzofcHe4QNqXGhcfz1/BVzQ/d2JKz370IFggEjze7Cqnte/oPtN/o+rakd3Oeodfavv75v+bXqXqX6Z3iWjn/St+2nf9CN984/wT/9NPgZ4QV8A7Dv+3BoXGvfzeqrqE0m+TO8L/a5O8rqq+sLcnUn7w5vo0v55Ir17EQDnDBm3t6oeAV7F/l8y+hxw3r6Z7kwG4D56f+p12LhHSXI8sLuqLgJ20LufIy2JASLtn3cAf5rkS/RuTs/nfwDnJLme3uWr+xcYO8hvAZuT3JLkb/inJ8D+N/AfuseLf32BcXO9Avh6d0nu2fS+Ml1aEp/CkiQ18QxEktTEAJEkNTFAJElNDBBJUhMDRJLUxACRJDUxQCRJTf4/XH2ycxztG/wAAAAASUVORK5CYII=\n",
      "text/plain": [
       "<Figure size 432x288 with 1 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "errors = []\n",
    "n_trees = np.arange(1, 120, 5) \n",
    "\n",
    "for n_tree in n_trees:\n",
    "    estimator = ensemble.GradientBoostingClassifier(max_depth=5, n_estimators=n_tree)\n",
    "    errors.append(model_selection.cross_val_score(estimator, X, y, cv=3).mean())\n",
    "    \n",
    "plot_scores(n_trees, errors, \"Iterations\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 418, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\ensemble\\_gb.py\", line 1097, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"C:\\Users\\Vasiliy\\anaconda3\\lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 172, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n"
     ]
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAZAAAAEWCAYAAABIVsEJAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjMuNCwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy8QVMy6AAAACXBIWXMAAAsTAAALEwEAmpwYAAAWCUlEQVR4nO3df/BddX3n8efLYOovLCoYMYkG3XRrpJWyGaSrO/utgEOQATp1RukqFOtk2YI/Vh03le0Odra7tnaq0lIzWX8MKIra4jRlo4DU77a6xUURQYpIQNlEIihtlQCWRd77xz2xl+v9/sjnm/u932/u8zFzJ+ecz+ec837zBV7fc869N6kqJEnaX48bdwGSpOXJAJEkNTFAJElNDBBJUhMDRJLUxACRJDUxQKQlJMm3k5w4omNPJ3n9KI6tyWSASJ3uf94PJzl8YPuNSSrJujGVtt+SXJjko+OuQwc3A0R6rG8BZ+5bSfILwBPHV460dBkg0mN9BDirb/1s4NL+CUlekeSrSX6YZFeSC/vGXpXkziRP7dY3JflukiOGnSzJa5PcleS+JBcMjD0uyZYkd3Tjn0zy9G5sXXdVtDnJ3Un2JHlrN3Yy8A7gVUn2Jvla32Gfm+SLSe5PcvXg1Za0PwwQ6bGuA56a5AVJVgCvAgZvBT1AL2QOA14B/IckZwBU1SeAvwUuSvIM4IPA66vqe4MnSrIBeD/wWuDZwDOANX1T3gicAfzbbvwfgIsHDvMrwHrg5cCWJCdW1WeB/wZ8oqqeUlUv6pv/68A5wDOBlcDb5vVPRRrCAJF+2r6rkJOAbwDf6R+squmqurmqHq2qm4CP0/uf/D7nAS8DpoG/rKorZzjPK4Erq+qvq+qfgN8BHu0b//fABVW1uxu/EHhlkkP65ryzqh6oqpuBD9N3+20GH66qb1bVQ8AngWPmmC/N6JC5p0gT5yPAXwNHMXD7CiDJi4F3AUfT+y3+Z4BP7Ruvqn9M8ingLcCvzXKeZwO7+vZ7IMl9fePPBT6dpD9Ufgys6lvf1bd8F/ALs3YG3+1bfhB4yhzzpRl5BSINqKq76D1MPwW4YsiUjwHbgbVV9bPAViD7BpMcA7yO3pXJRbOcag+wtm+/J9G7jbXPLmBTVR3W93pCVfVfEa3tW34OcPe+NmZtUjoADBBpuN8EXlZVDwwZOxT4+6r6UZLj6D1XACDJE+g9M3kHvWcNq5P81gzn+DPg1CQvTbIS+F0e+9/kVuD3kjy3O/YRSU4fOMbvJHlSkhd25/tEt/0eYF0S/xvXyPgvlzREVd1RVV+eYfi3gN9Ncj/wX+g9S9jnvwO7q+r93XOL1wD/Ncn6Iee4hd7zko/Ruxr5B2B335T30bvSubo713XAiwcO87+AncC1wB9W1dXd9n231O5LcsN8epb2V/wLpaTlp/tQ47eAx1fVI2MuRxPKKxBJUhMDRJLUxFtYkqQmXoFIkppM1AcJDz/88Fq3bt24y9hvDzzwAE9+8pPHXcaimbR+wZ4nxXLt+Stf+cr3q+qnvs9togJk3bp1fPnLM70zc+manp5mampq3GUsmknrF+x5UizXnpPcNWy7t7AkSU0MEElSEwNEktTEAJEkNTFAJElNDBBJUhMDRJLUxACRJDUxQCRJTQwQSVITA0SS1MQAkSQ1MUAkSU0MEElSEwNEktTEAJEkNTFAJElNDBBJUhMDRJLUxACRJDUxQCRJTQwQSVITA0SS1MQAkSQ1MUAkSU3GGiBJTk5yW5KdSbYMGU+Si7rxm5IcOzC+IslXk1y5eFVLkmCMAZJkBXAxsAnYAJyZZMPAtE3A+u61GXj/wPibgFtHXKokaYhxXoEcB+ysqjur6mHgcuD0gTmnA5dWz3XAYUmOBEiyBngF8IHFLFqS1HPIGM+9GtjVt74bePE85qwG9gDvBd4OHDrbSZJspnf1wqpVq5ienl5IzWOxd+/eZVl3q0nrF+x5UhxsPY8zQDJkW81nTpJTgXur6itJpmY7SVVtA7YBbNy4saamZp2+JE1PT7Mc6241af2CPU+Kg63ncd7C2g2s7VtfA9w9zzkvAU5L8m16t75eluSjoytVkjRonAFyPbA+yVFJVgKvBrYPzNkOnNW9G+t44AdVtaeqfruq1lTVum6/v6qq1yxq9ZI04cZ2C6uqHklyPnAVsAL4UFXdkuTcbnwrsAM4BdgJPAicM656JUmPNc5nIFTVDnoh0b9ta99yAefNcYxpYHoE5UmSZuEn0SVJTQwQSVITA0SS1MQAkSQ1MUAkSU0MEElSEwNEktTEAJEkNTFAJElNDBBJUhMDRJLUxACRJDUxQCRJTQwQSVITA0SS1MQAkSQ1MUAkSU0MEElSEwNEktTEAJEkNTFAJElNDBBJUhMDRJLUxACRJDUxQCRJTQwQSVITA0SS1MQAkSQ1MUAkSU0MEElSk7EGSJKTk9yWZGeSLUPGk+SibvymJMd229cm+XySW5PckuRNi1+9JE22sQVIkhXAxcAmYANwZpINA9M2Aeu712bg/d32R4C3VtULgOOB84bsK0kaoXFegRwH7KyqO6vqYeBy4PSBOacDl1bPdcBhSY6sqj1VdQNAVd0P3AqsXsziJWnSjTNAVgO7+tZ389MhMOecJOuAXwK+dOBLlCTN5JAxnjtDttX+zEnyFODPgTdX1Q+HniTZTO/2F6tWrWJ6erqp2HHau3fvsqy71aT1C/Y8KQ62nscZILuBtX3ra4C75zsnyePphcdlVXXFTCepqm3ANoCNGzfW1NTUggtfbNPT0yzHultNWr9gz5PiYOt5nLewrgfWJzkqyUrg1cD2gTnbgbO6d2MdD/ygqvYkCfBB4Naq+qPFLVuSBGO8AqmqR5KcD1wFrAA+VFW3JDm3G98K7ABOAXYCDwLndLu/BHgtcHOSG7tt76iqHYvYgiRNtHHewqL7H/6OgW1b+5YLOG/Ifl9g+PMRSdIi8ZPokqQmBogkqYkBIklqYoBIkpoYIJKkJgaIJKmJASJJamKASJKaGCCSpCYGiCSpiQEiSWpigEiSmhggkqQmBogkqYkBIklqYoBIkpoYIJKkJgaIJKmJASJJamKASJKaGCCSpCYGiCSpiQEiSWpigEiSmhggkqQmBogkqcmsAZLkNX3LLxkYO39URUmSlr65rkDe0rf8xwNjrzvAtUiSlpG5AiQzLA9blyRNkLkCpGZYHrYuSZogh8wx/vNJbqJ3tfH8bplu/XkjrUyStKTNFSAvGOXJk5wMvA9YAXygqt41MJ5u/BTgQeA3quqG+ewrSRqtWW9hVdVd/S9gL3AscHi33izJCuBiYBOwATgzyYaBaZuA9d1rM/D+/dhXkjRCc72N98okR3fLRwJfp/fuq48kefMCz30csLOq7qyqh4HLgdMH5pwOXFo91wGHdXXMZ19J0gjNdQvrqKr6erd8DnBNVZ2V5FDgi8B7F3Du1cCuvvXdwIvnMWf1PPcFIMlmelcvrFq1iunp6QWUPB579+5dlnW3mrR+wZ4nxcHW81wB8v/6lk8A/gdAVd2f5NEFnnvY24AH39k105z57NvbWLUN2AawcePGmpqa2o8Sl4bp6WmWY92tJq1fsOdJcbD1PFeA7EryBnq/4R8LfBYgyROBxy/w3LuBtX3ra4C75zln5Tz2lSSN0FyfA/lN4IXAbwCvqqp/7LYfD3x4gee+Hlif5KgkK4FXA9sH5mwHzkrP8cAPqmrPPPeVJI3QrFcgVXUvcO6Q7Z8HPr+QE1fVI933aV1F7624H6qqW5Kc241vBXbQewvvTnpv4z1ntn0XUo8kaf/MGiBJZv2tvqpOW8jJq2oHvZDo37a1b7mA8+a7ryRp8cz1DOSX6b3b6ePAl/D7ryRJnbkC5FnAScCZwK8D/xP4uLeLJElzfRL9x1X12ao6m96D853AdPfOLEnSBJvrCoQkPwO8gt5VyDrgIuCK0ZYlSVrq5nqIfglwNPAZ4J19n0qXJE24ua5AXgs8APwc8Mbel+MCvYfpVVVPHWFtkqQlbK7Pgcz1QUNJ0oQyICRJTQwQSVITA0SS1MQAkSQ1MUAkSU0MEElSEwNEktTEAJEkNTFAJElNDBBJUhMDRJLUxACRJDUxQCRJTQwQSVITA0SS1MQAkSQ1MUAkSU0MEElSEwNEktTEAJEkNTFAJElNDBBJUhMDRJLUZCwBkuTpSa5Jcnv359NmmHdyktuS7EyypW/7u5N8I8lNST6d5LBFK16SBIzvCmQLcG1VrQeu7dYfI8kK4GJgE7ABODPJhm74GuDoqvpF4JvAby9K1ZKknxhXgJwOXNItXwKcMWTOccDOqrqzqh4GLu/2o6qurqpHunnXAWtGW64kadC4AmRVVe0B6P585pA5q4Fdfeu7u22DXgd85oBXKEma1SGjOnCSzwHPGjJ0wXwPMWRbDZzjAuAR4LJZ6tgMbAZYtWoV09PT8zz90rF3795lWXerSesX7HlSHGw9jyxAqurEmcaS3JPkyKrak+RI4N4h03YDa/vW1wB39x3jbOBU4ISqKmZQVduAbQAbN26sqamp/epjKZienmY51t1q0voFe54UB1vP47qFtR04u1s+G/iLIXOuB9YnOSrJSuDV3X4kORn4T8BpVfXgItQrSRowrgB5F3BSktuBk7p1kjw7yQ6A7iH5+cBVwK3AJ6vqlm7/PwEOBa5JcmOSrYvdgCRNupHdwppNVd0HnDBk+93AKX3rO4AdQ+b9i5EWKEmak59ElyQ1MUAkSU0MEElSEwNEktTEAJEkNTFAJElNDBBJUhMDRJLUxACRJDUxQCRJTQwQSVITA0SS1MQAkSQ1MUAkSU0MEElSEwNEktTEAJEkNTFAJElNDBBJUhMDRJLUxACRJDUxQCRJTQwQSVITA0SS1MQAkSQ1MUAkSU0MEElSEwNEktTEAJEkNTFAJElNDBBJUpOxBEiSpye5Jsnt3Z9Pm2HeyUluS7IzyZYh429LUkkOH33VkqR+47oC2QJcW1XrgWu79cdIsgK4GNgEbADOTLKhb3wtcBLwfxelYknSY4wrQE4HLumWLwHOGDLnOGBnVd1ZVQ8Dl3f77fMe4O1AjbBOSdIMDhnTeVdV1R6AqtqT5JlD5qwGdvWt7wZeDJDkNOA7VfW1JLOeKMlmYDPAqlWrmJ6eXnj1i2zv3r3Lsu5Wk9Yv2POkONh6HlmAJPkc8KwhQxfM9xBDtlWSJ3XHePl8DlJV24BtABs3bqypqal5nn7pmJ6eZjnW3WrS+gV7nhQHW88jC5CqOnGmsST3JDmyu/o4Erh3yLTdwNq+9TXA3cDzgaOAfVcfa4AbkhxXVd89YA1IkmY1rmcg24Gzu+Wzgb8YMud6YH2So5KsBF4NbK+qm6vqmVW1rqrW0QuaYw0PSVpc4wqQdwEnJbmd3jup3gWQ5NlJdgBU1SPA+cBVwK3AJ6vqljHVK0kaMJaH6FV1H3DCkO13A6f0re8AdsxxrHUHuj5J0tz8JLokqYkBIklqYoBIkpoYIJKkJgaIJKmJASJJamKASJKaGCCSpCYGiCSpiQEiSWpigEiSmhggkqQmBogkqYkBIklqYoBIkpoYIJKkJgaIJKmJASJJamKASJKaGCCSpCYGiCSpiQEiSWpigEiSmhggkqQmqapx17BoknwPuGvcdTQ4HPj+uItYRJPWL9jzpFiuPT+3qo4Y3DhRAbJcJflyVW0cdx2LZdL6BXueFAdbz97CkiQ1MUAkSU0MkOVh27gLWGST1i/Y86Q4qHr2GYgkqYlXIJKkJgaIJKmJAbIEJHl6kmuS3N79+bQZ5p2c5LYkO5NsGTL+tiSV5PDRV70wC+05ybuTfCPJTUk+neSwRSt+P83j55YkF3XjNyU5dr77LlWtPSdZm+TzSW5NckuSNy1+9W0W8nPuxlck+WqSKxev6gWqKl9jfgF/AGzplrcAvz9kzgrgDuB5wErga8CGvvG1wFX0Pih5+Lh7GnXPwMuBQ7rl3x+2/1J4zfVz6+acAnwGCHA88KX57rsUXwvs+Ujg2G75UOCbB3vPfeNvAT4GXDnufub78gpkaTgduKRbvgQ4Y8ic44CdVXVnVT0MXN7tt897gLcDy+VdEQvquaqurqpHunnXAWtGW26zuX5udOuXVs91wGFJjpznvktRc89VtaeqbgCoqvuBW4HVi1l8o4X8nEmyBngF8IHFLHqhDJClYVVV7QHo/nzmkDmrgV1967u7bSQ5DfhOVX1t1IUeQAvqecDr6P1mtxTNp4eZ5sy3/6VmIT3/RJJ1wC8BXzrwJR5wC+35vfR+AXx0RPWNxCHjLmBSJPkc8KwhQxfM9xBDtlWSJ3XHeHlrbaMyqp4HznEB8Ahw2f5Vt2jm7GGWOfPZdylaSM+9weQpwJ8Db66qHx7A2kalueckpwL3VtVXkkwd6MJGyQBZJFV14kxjSe7Zd/neXdLeO2TabnrPOfZZA9wNPB84Cvhakn3bb0hyXFV994A10GCEPe87xtnAqcAJ1d1EXoJm7WGOOSvnse9StJCeSfJ4euFxWVVdMcI6D6SF9PxK4LQkpwBPAJ6a5KNV9ZoR1ntgjPshjK8CeDePfaD8B0PmHALcSS8s9j2ke+GQed9meTxEX1DPwMnA3wFHjLuXOfqc8+dG7953/8PV/7M/P/Ol9lpgzwEuBd477j4Wq+eBOVMso4foYy/AVwE8A7gWuL378+nd9mcDO/rmnULvXSl3ABfMcKzlEiAL6hnYSe9+8o3da+u4e5ql15/qATgXOLdbDnBxN34zsHF/fuZL8dXaM/BSerd+bur72Z4y7n5G/XPuO8ayChC/ykSS1MR3YUmSmhggkqQmBogkqYkBIklqYoBIkpoYINIMkvw4yY1Jvp7kU92n/sdd01SSfz3uOiQwQKTZPFRVx1TV0cDD9N7TP6cko/yGhylgvwJkxPVogvk5EGkGSfZW1VO65XOBX6T3SeL/TO/TxvcB/66q7klyIb0PQa4Dvg+8A/gI8OTucOdX1f/uvuvoncA9wDHAFfQ+VPYm4InAGVV1R5IjgK3Ac7r93wx8h943D/8Y+B7wBuAbg/Oq6otD6vk94MNd3Y8Dfq2qbj8A/5g0wfzNRJpD9xv8JuCzwBeA46uqkrye3jeovrWb+q+Al1bVQ93trpOq6kdJ1gMfBzZ2814EvAD4e3pff/GBqjqu+8uT3kAvLN4HvKeqvpDkOcBVVfWCJFuBvVX1h11tHxuc1x17sJ4/Bt5XVZclWUnv76+QFsQAkWb2xCQ3dst/A3wQ+JfAJ7ovgFwJfKtv/vaqeqhbfjzwJ0mOoXfF8HN9866v7qvsk9wBXN1tvxn4lW75RGBD9wWZ0PuCvUOH1DjbvP56/ha4oPt7J67w6kMHggEizeyhqjqmf0P3m/wfVdX27nbUhX3DD/Qt/0d6t6leRO+W0Y/6xv6pb/nRvvVH+ef/Jh8H/HJfAOw7/2CNs837ST1V9bEkX6L3hX5XJXl9Vf3V4MGk/eFDdGn//Cy9ZxEAZ88xb09VPQq8lv2/ZXQ1cP6+le5KBuB+en/V61zzHiPJ84A7q+oiYDu95znSghgg0v65EPhUkr+h93B6Jn8KnJ3kOnq3rx6YZe4wbwQ2Jrkpyd/xz+8A+0vgV7u3F/+bWeYNehXw9e6W3M/T+8p0aUF8F5YkqYlXIJKkJgaIJKmJASJJamKASJKaGCCSpCYGiCSpiQEiSWry/wG9/8QNQXCbigAAAABJRU5ErkJggg==\n",
      "text/plain": [
       "<Figure size 432x288 with 1 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "d_errors = []\n",
    "n_depth = np.arange(1, 20, 1) \n",
    "\n",
    "for d in n_depth:\n",
    "    estimator = ensemble.GradientBoostingClassifier(max_depth=d, n_estimators=50)\n",
    "    d_errors.append(model_selection.cross_val_score(estimator, X, y, cv=3).mean())\n",
    "\n",
    "plot_scores(n_depth, d_errors, \"Max depth\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Задание 5\n",
    "\n",
    "Сравните получаемое с помощью градиентного бустинга качество с качеством работы линейной регрессии. \n",
    "\n",
    "Для этого обучите `LinearRegression` из `sklearn.linear_model` (с параметрами по умолчанию) на обучающей выборке и оцените для прогнозов полученного алгоритма на тестовой выборке `RMSE`. Полученное качество - ответ в **пункте 5**. \n",
    "\n",
    "В данном примере качество работы простой модели должно было оказаться хуже, но не стоит забывать, что так бывает не всегда. В заданиях к этому курсу вы еще встретите пример обратной ситуации."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "8.216405907793146\n"
     ]
    }
   ],
   "source": [
    "regr = linear_model.LinearRegression()\n",
    "regr.fit(X_train, y_train)\n",
    "print(metrics.mean_squared_error(y_test, regr.predict(X_test))**0.5)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 1
}
